export type City = "saint_petersburg" | "seoul" | "singapore" | "san_francisco" | "global";

export type EventTemplateCategory = "economic" | "tech" | "corporate" | "market" | "city";

export type EventTemplate = {
  id: string;
  category: EventTemplateCategory;
  weight: number;
  cooldownHours: number;
  titlePattern: string;
  descriptionPattern: string;
  targets: string[];
  allowedCities: City[];
  duration: number[];
};

export const EVENT_TEMPLATES: EventTemplate[] = [
  {
    id: "chip_shortage",
    category: "tech",
    weight: 10,
    cooldownHours: 72,
    titlePattern: "Дефицит {target}",
    descriptionPattern: "На рынке возник дефицит категории {target}.",
    targets: ["processor", "memory", "camera", "battery"],
    allowedCities: ["global", "seoul", "singapore"],
    duration: [12, 24, 36],
  },
  {
    id: "battery_breakthrough",
    category: "tech",
    weight: 8,
    cooldownHours: 72,
    titlePattern: "Прорыв в {target}",
    descriptionPattern: "Новая технология в категории {target} ускорила производство.",
    targets: ["battery", "power", "smartphones"],
    allowedCities: ["global", "seoul", "san_francisco"],
    duration: [12, 18, 24],
  },
  {
    id: "ai_revolution",
    category: "tech",
    weight: 7,
    cooldownHours: 96,
    titlePattern: "AI-революция в {target}",
    descriptionPattern: "AI-инструменты резко подняли эффективность в {target}.",
    targets: ["research", "design", "analytics"],
    allowedCities: ["global", "san_francisco", "seoul"],
    duration: [24, 36, 48],
  },
  {
    id: "market_boom",
    category: "market",
    weight: 9,
    cooldownHours: 72,
    titlePattern: "Рыночный бум: {target}",
    descriptionPattern: "Спрос на {target} резко вырос.",
    targets: ["smartphones", "tablets", "laptops", "smartwatches"],
    allowedCities: ["global", "singapore", "san_francisco"],
    duration: [12, 24, 36],
  },
  {
    id: "market_crash",
    category: "market",
    weight: 6,
    cooldownHours: 96,
    titlePattern: "Просадка рынка: {target}",
    descriptionPattern: "Спрос на {target} упал из-за перенасыщения.",
    targets: ["smartphones", "tablets", "laptops", "smartwatches"],
    allowedCities: ["global"],
    duration: [12, 24],
  },
  {
    id: "investment_wave",
    category: "corporate",
    weight: 8,
    cooldownHours: 72,
    titlePattern: "Инвест-волна в {target}",
    descriptionPattern: "Инвесторы усилили поток капитала в {target}.",
    targets: ["seoul", "singapore", "san_francisco", "saint_petersburg"],
    allowedCities: ["global", "singapore"],
    duration: [12, 24, 36],
  },
  {
    id: "startup_boom",
    category: "corporate",
    weight: 8,
    cooldownHours: 72,
    titlePattern: "Бум стартапов: {target}",
    descriptionPattern: "Город {target} переживает новый стартап-бум.",
    targets: ["saint_petersburg", "seoul", "singapore", "san_francisco"],
    allowedCities: ["global"],
    duration: [12, 24],
  },
  {
    id: "chip_factory_expansion",
    category: "tech",
    weight: 7,
    cooldownHours: 72,
    titlePattern: "Расширение фабрик: {target}",
    descriptionPattern: "Производственные мощности по {target} увеличены.",
    targets: ["processor", "memory", "security_chip"],
    allowedCities: ["global", "seoul"],
    duration: [12, 24, 36],
  },
  {
    id: "supply_chain_crisis",
    category: "economic",
    weight: 7,
    cooldownHours: 96,
    titlePattern: "Кризис цепочек поставок: {target}",
    descriptionPattern: "Логистика в категории {target} нарушена.",
    targets: ["processor", "battery", "camera", "memory"],
    allowedCities: ["global", "singapore", "saint_petersburg"],
    duration: [24, 36],
  },
  {
    id: "tech_conference",
    category: "city",
    weight: 8,
    cooldownHours: 72,
    titlePattern: "Tech-конференция в {target}",
    descriptionPattern: "Крупная конференция усилила найм и исследования в {target}.",
    targets: ["saint_petersburg", "seoul", "singapore", "san_francisco"],
    allowedCities: ["global"],
    duration: [12, 24],
  },
  {
    id: "startup_grants",
    category: "city",
    weight: 9,
    cooldownHours: 72,
    titlePattern: "Гранты стартапам в {city}",
    descriptionPattern: "Город поддержал новые IT-команды: исследования и запуск продуктов ускорились.",
    targets: ["all"],
    allowedCities: ["saint_petersburg", "seoul", "singapore", "san_francisco"],
    duration: [12, 24, 36],
  },
  {
    id: "electronics_shortage",
    category: "city",
    weight: 8,
    cooldownHours: 72,
    titlePattern: "Дефицит электроники в {city}",
    descriptionPattern: "Поставки компонентов просели: техника дорожает, а производство замедляется.",
    targets: ["all"],
    allowedCities: ["saint_petersburg", "seoul", "singapore", "san_francisco"],
    duration: [12, 24],
  },
  {
    id: "tax_audit",
    category: "city",
    weight: 6,
    cooldownHours: 96,
    titlePattern: "Налоговая проверка в {city}",
    descriptionPattern: "Компании действуют осторожнее: найм и развитие временно замедлены.",
    targets: ["all"],
    allowedCities: ["saint_petersburg", "seoul", "singapore", "san_francisco"],
    duration: [12, 24],
  },
  {
    id: "it_forum",
    category: "city",
    weight: 8,
    cooldownHours: 72,
    titlePattern: "IT-форум в {city}",
    descriptionPattern: "В город приехали специалисты и инвесторы: рынок оживился, знания и зарплаты растут.",
    targets: ["all"],
    allowedCities: ["saint_petersburg", "seoul", "singapore", "san_francisco"],
    duration: [12, 24, 36],
  },
  {
    id: "global_recession",
    category: "economic",
    weight: 5,
    cooldownHours: 120,
    titlePattern: "Глобальная рецессия",
    descriptionPattern: "Рынок стал осторожнее: спрос и зарплаты временно просели.",
    targets: ["all"],
    allowedCities: ["global"],
    duration: [24, 36, 48],
  },
  {
    id: "gaming_trend",
    category: "market",
    weight: 9,
    cooldownHours: 72,
    titlePattern: "Игровой тренд: {target}",
    descriptionPattern: "Аудитория резко повысила интерес к {target}.",
    targets: ["gaming_gadgets", "smartphones", "laptops"],
    allowedCities: ["global", "seoul", "san_francisco"],
    duration: [12, 24, 36],
  },
];
